CREATE TABLE "GCG_3555_BOM_RTR_EST"(
 "BIRUNID" INTEGER NOT NULL ,
 "SEQ" CHAR(20) NOT NULL ,
 "PART" CHAR(20) NOT NULL ,
 "LMO" CHAR(1) NOT NULL ,
 "SOURCE" CHAR(2),
 "QUANTITY" DOUBLE,
 "SETUP" DOUBLE);